# Default Gladius Control Daemon Config
version               = "0.5.0"
build                 = 20180821

[logging]
  path                = "./logs/"

[directory]
  base                = "$home/.config/gladius/"
  wallet              = "wallet"

[blockchain]
  provider            = "https://ropsten.infura.io/tjqLYxxGIUp0NylVCiWw"
  marketAddress       = "0xad5c2c9eb5630780808e9333a08fcedec0afd03f"

[nodeManager]
  [nodeManager.config]
    name              = "GladiusNodeControlDaemon"
    displayName       = "Gladius Node Manager"
    description       = "Gladius Control Daemon"
    debug             = true
    port              = "3001"

[poolManager]
  [poolManager.config]
    name              = "GladiusPoolControlDaemon"
    displayName       = "Gladius Pool Manager"
    description       = "Gladius Control Daemon"
    debug             = true
    port              = "3000"
  [poolManager.database]
      type            = "postgres"
      host            = "127.0.0.1"
      port            = "5432"
      user            = "nate"
      name            = "nate"
      password        = "password"
      ssl             = false

[applicationServer]
  [applicationServer.config]
    name              = "GladiusApplicationServerControlDaemon"
    displayName       = "Gladius Application Server"
    description       = "Gladius Control Daemon"
    debug             = true
    port              = "3333"
  [applicationServer.database]
    type              = "postgres"
    host              = "127.0.0.1"
    port              = "5432"
    user              = "nate"
    name              = "nate"
    password          = "password"
    ssl               = false
