# Config
[[constraint]]
  name = "github.com/spf13/viper"
  version = "=1.1.0"

# Gladius Packages
[[constraint]]
  name = "github.com/gladiusio/gladius-utils"
  version = "~0.3.0"

[[constraint]]
  name = "github.com/gladiusio/gladius-application-server"
  branch = "master"

# Blockchain
[[constraint]]
  name = "github.com/ethereum/go-ethereum"
  version = "1.8.7"

# API
[[constraint]]
  name = "github.com/gorilla/handlers"
  version = "=1.3.0"

[[constraint]]
  name = "github.com/gorilla/mux"
  version = "=1.6.1"

[[constraint]]
  branch = "master"
  name = "github.com/buger/jsonparser"

# P2P
[[constraint]]
  name = "github.com/tdewolff/minify"
  version = "=2.3.5"

[[constraint]]
  name = "github.com/hashicorp/memberlist"
  version = "=0.1.0"

[[constraint]]
  name = "github.com/satori/go.uuid"
  version = "=1.2.0"

[[constraint]]
  name = "github.com/deckarep/golang-set"
  version = "=1.7"
